### ISSUE TITLE
can't see helm chart information if the chart is uploaded as a form of folder. 

### ISSUE THREAD

**Issue by jerryum** [NexClipper/exporterhub.io#105]
I found that a helm chart for Node-exporter merged 
https://github.com/NexClipper/exporterhub.io/tree/main/contents/Node-Exporter/helm-chart

It doesn't have a file format - node-exporter_helm.yaml but with folder structure and can't show what we have in the folder. We should be able to show "folder" type of helm chart??

![image](https://user-images.githubusercontent.com/84423164/131900778-8ade03b4-d497-4eb0-bd1c-7bcfb884363a.png)

**Comment by ralfyang** [comment]
It's an issue with the directory tree of source code in the exporterhub.io. we are fixing it now as you told that.
Thanks :) @jerryum

**Comment by ralfyang** [comment]
This issue has been closed by #136
