### ISSUE TITLE
create github action file for CI/CD

### ISSUE THREAD

**Issue by bart2001** [NexClipper/exporterhub.io#108]
- create github action file for CI/CD

**Comment by ralfyang** [comment]
![image](https://user-images.githubusercontent.com/4043594/133025521-42e7ade2-221a-4326-902e-bc46184a28f7.png)

It's working on normally! Thanks :)
![image](https://user-images.githubusercontent.com/4043594/133025572-e1a2f924-a3c4-4b76-bc17-ecc16ae1c4c3.png)

**Comment by ralfyang** [comment]
This ticket has been closed @bart2001
