### ISSUE TITLE
Need to move the `Search bar` from GNB to Main

### ISSUE THREAD

**Issue by ralfyang** [NexClipper/exporterhub.io#64]
`Search bar` is not working in the sub page, So it'll has to be move to landing-main page from GNB

**Comment by bart2001** [comment]
![image](https://user-images.githubusercontent.com/18025021/131511780-a31661fb-c172-4f91-8ceb-4259cc8c2494.png)
As far as I understand, moving `Searchbar` right above Filter Selectbox (Most populer/Recent/Trending) would be enough?

**Comment by ralfyang** [comment]
This issue has been closed by #136
