### ISSUE TITLE
Need a function for cleansing the export

### ISSUE THREAD

**Issue by chloe-codes1** [NexClipper/exporterhub.io#71]
# Description
Need to remove function for cleansing the export

# Details
### Specify project
`Client`

### Is your feature request related to a problem? Please describe.
exporterhub.io does not support deleting exports.

### Describe the solution you'd like
I would like exporterhub.io `admins` to delete exports in the exporterhub.io page

**Comment by ralfyang** [comment]
![image](https://user-images.githubusercontent.com/4043594/130772594-d1f6ab72-c317-49f1-9ce4-93b3ab831bc2.png)
Want to remove it in the exporterhub.io page by admin

**Comment by ralfyang** [comment]
This issue has been closed by #136
