### ISSUE TITLE
Whether to remove 'Search' component in Detail of Exporter

### ISSUE THREAD

**Issue by Joylish** [NexClipper/exporterhub.io#95]
During a recent meeting, it was said that it would be better if there was no search bar on the detail page. 
It would be good to think about whether it would be better to delete the search bar from the detail page.

## Now
![image](https://user-images.githubusercontent.com/52230415/131380741-b061cf56-4d92-40a1-9e13-4ac196944e71.png)

## After edit
![image](https://user-images.githubusercontent.com/52230415/131380904-38963fbd-8148-450c-bb74-f3409f5cc262.png)

**Comment by minmin9324** [comment]
I have plan to move the ‘Search’ component in the ExporterHub Page, so that it is not visible in the detail page.

**Comment by ralfyang** [comment]
This issue has been closed by #136
